# herdr-prs repo list — written by pick-repos.sh on 2026-08-06 08:20.
# One repo per line: owner/repo, optional TAB + local clone path.

vippsas/pling-backend	/Users/andreas/Development/Rider/pling-backend
vippsas/odd-offboarding	/Users/andreas/Development/Rider/odd-offboarding
vippsas/ongoing-due-diligence	/Users/andreas/Development/Rider/ongoing-due-diligence
vippsas/risk-usage-normalisation-engine	/Users/andreas/Development/Rider/risk-usage-normalisation-engine
vippsas/risky-business-country	/Users/andreas/Development/Rider/risky-business-country
vippsas/risky-business-infrastructure
vippsas/risky-business-pipelines	/Users/andreas/Development/Rider/risky-business-pipelines
vippsas/risky-business-slack-bot	/Users/andreas/Development/pyCharm/risky-business-slack-bot
vippsas/risky-business-web-application	/Users/andreas/Development/Rider/risky-business-web-application
vippsas/suspected-merchant	/Users/andreas/Development/Rider/suspected-merchant
vippsas/terms-and-conditions	/Users/andreas/Development/Rider/terms-and-conditions
vippsas/user-deletion-engine	/Users/andreas/Development/Rider/user-deletion-engine
vippsas/vm-night-owl	/Users/andreas/Development/Rider/vm-night-owl
vippsas/vm-shared-domain-errorqueue	/Users/andreas/Development/Rider/vm-shared-domain-errorqueue
vippsas/vm-shared-replay	/Users/andreas/Development/Rider/vm-shared-replay
